### ISSUE TITLE
ノードの移動時、移動後にリンクが追従してこないことがある

### ISSUE THREAD

**Issue by tsunashima-katsuyuki** [ss-study/stickit#40]
発生条件不明。
現在調査中。

**Comment by ss-study** [comment]
ノードを3つ追加して、それぞれをA, B, Cとする。
A, BからCに向けてリンクを追加する。
Cを削除して、先ほど追加した2つのリンクが同時に消える。
AからBへリンクを追加した後に、ノードを移動するとこのバグが発生する。

**Comment by ss-study** [comment]
> ノードを3つ追加して、それぞれをA, B, Cとする。
> A, BからCに向けてリンクを追加する。
> Cを削除して、先ほど追加した2つのリンクが同時に消える。
> AからBへリンクを追加した後に、ノードを移動するとこのバグが発生する。

追加するリンクの向きは関係なく発生する模様。
削除処理の時に、ローカルで持っているリンクの接続情報がおかしくなっている可能性あり。
上記が原因でこの問題が発生している可能性がある。

**Comment by ss-study** [comment]
ノード削除後に、ノードに繋がるリンクのリストに削除済みのデータが残っていることが判明した。
直接削除済みの残ったデータのみを取り除くことで、移動時にリンクを追従させる処理は正しく動くと思われることがわかった。
これの改修作業に入る。

**Comment by ss-study** [comment]
見積工数: 6h

**Comment by ss-study** [comment]
リンクのidと、リンク操作のためのlineオブジェクトを別々に管理していたものを、1つのMapで管理したい。
